name: push-latest

# trigger on push to master
# only on Dockerfile related modifications
on:
  push:
    branches:
      - "master"
      - "**"
    paths:
      - "Dockerfile"
      - "supported_versions.json"
      - "hashicorp.asc"
      - "tests/**"
      - ".dockerignore"
      - "hadolint.yaml"
      - ".github/workflows/push-latest.yml"

jobs:
  load_supported_platforms:
    runs-on: ubuntu-22.04

    outputs:
      matrix: ${{ steps.set-matrix.outputs.platforms }}

    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Save supported platforms as output
        id: set-matrix
        run: |
          PLATFORMS=$(cat ./supported_platforms.json)
          PLATFORMS="${PLATFORMS//'%'/%25}"
          PLATFORMS="${PLATFORMS//$'\n'/%0A}"
          PLATFORMS="${PLATFORMS//$'\r'/%0D}"
          echo "::set-output name=platforms::${PLATFORMS}"

  build_push_latest:
    runs-on: ubuntu-22.04

    strategy:
      matrix: ${{ fromJSON(needs.load_supported_platforms.outputs.platforms) }}

    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Retrieve latest suported versions
        run: |
          echo "TF_VERSION=$(jq -r '.tf_versions | sort | .[-1]' supported_versions.json)" >> $GITHUB_ENV
          echo "AWS_VERSION=$(jq -r '.awscli_versions | sort | .[-1]' supported_versions.json)" >> $GITHUB_ENV

      - name: Login to Docker Hub registry
        run: echo '${{ secrets.DOCKERHUB_PAT }}' | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push Docker images
        uses: docker/build-push-action@v3
        with:
          context: .
          platforms: ${{ matrix.platforms}}
          build-args: |
            TERRAFORM_VERSION=${{ env.TF_VERSION }}
            AWS_CLI_VERSION=${{ env.AWS_VERSION }}
          tags: zenika/terraform-aws-cli:latest
          push: true
